name: Publish NuGet

on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true

#permissions:

jobs:
  build-test:
    name: Publish NuGet
    runs-on: ubuntu-latest
    steps:
    - name: Download NuGet Packages
      uses: actions/download-artifact@v6
      with:
        name: nuget-packages
        path: nuget-packages

    - name: .NET NuGet Push
      run: dotnet nuget push nuget-packages/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
