name: Publish NuGet

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name containing NuGet packages to publish'
        default: 'nuget-packages'
        required: false
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

#permissions:

jobs:
  publish-nuget:
    name: Publish NuGet
    runs-on: ubuntu-latest
    steps:
    - name: Download NuGet Packages
      uses: actions/download-artifact@v7
      with:
        name: ${{ inputs.artifact-name }}
        path: nuget-packages

    - name: .NET NuGet Push
      run: dotnet nuget push nuget-packages/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
